# Site Settings and General Information
title: Ahmed Khaled
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pykhaled.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed

# jekyll-seo-tag settings
social:
  name: Ahmed Khaled
  links:
    - https://twitter.com/pykhaled
    - https://facebook.com/pykhaled
    - http://linkedin.com/in/pykhaled
    - https://github.com/pykhaled

# logo: /assets/img/logo/MvvmCross-avatar.png