# Sites settings 
title: Ahmed Khaled - Full Stack Developer
email: ahmedaka@icloud.com
description: 
baseurl: ""
url: http://pykhaled.com
twitter_username: pykhaled
github_username: pykhaled

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
gems: [
    
]